//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeBL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstTable
    {
        public int SlNo { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
    }
}
